spring.application.name=qeat
spring.config.import=optional:file:.env[.properties]
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
server.port=${SERVER_PORT:9090}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/qeat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci}
spring.datasource.username=${DB_USERNAME:qeat_user}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

file.dir=${FILE_DIR:./uploads}
file.url-prefix=${FILE_URL_PREFIX:/uploads}
qr.base-url=${QR_BASE_URL:http://localhost:5173}
