spring.application.name=Qeat
spring.config.import=optional:file:.env[.properties]
server.port=9090

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:1000/qeat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
spring.datasource.username=${DB_USERNAME:qeat_user}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

file.dir=${FILE_DIR:/Users/kimjunghyun/Qeat/uploads}
file.url-prefix=${FILE_URL_PREFIX:/uploads}
qr.base-url=${QR_BASE_URL:http://localhost:9090}
